function dX_obs_dq = dX_obs_dq(in1,in2,dt)
%DX_OBS_DQ
%    DX_OBS_DQ = DX_OBS_DQ(IN1,IN2,DT)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    31-Aug-2012 16:42:03

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q1.*v2.*2.0;
t3 = q2.*v3.*2.0;
t20 = q4.*v1.*2.0;
t4 = t2-t20+t3;
t5 = dt.*t4;
t6 = q1.*v3.*2.0;
t7 = q3.*v1.*2.0;
t18 = q2.*v2.*2.0;
t8 = -t18+t6+t7;
t9 = q2.*v1.*2.0;
t10 = q3.*v2.*2.0;
t11 = q4.*v3.*2.0;
t12 = t10+t11+t9;
t13 = dt.*t12;
t14 = q1.*v1.*2.0;
t15 = q4.*v2.*2.0;
t21 = q3.*v3.*2.0;
t16 = t14+t15-t21;
t17 = dt.*t16;
t19 = dt.*t8;
dX_obs_dq = reshape([t17,t5,t19,t13,t19,-t5,-dt.*t8,t13,t17,t5,-t17,t13],[3, 4]);
